import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const appSource = fs.readFileSync(path.join(process.cwd(), 'src', 'App.vue'), 'utf8')
const apiSource = fs.readFileSync(path.join(process.cwd(), 'src', 'api.ts'), 'utf8')
const cssSource = fs.readFileSync(path.join(process.cwd(), 'src', 'styles.css'), 'utf8')
const packageSource = fs.readFileSync(path.join(process.cwd(), 'package.json'), 'utf8')
const splitRevealPath = path.join(process.cwd(), 'src', 'components', 'SplitRevealText.vue')
const splitRevealSource = fs.existsSync(splitRevealPath) ? fs.readFileSync(splitRevealPath, 'utf8') : ''
const gridDistortionPath = path.join(process.cwd(), 'src', 'components', 'GridDistortion.vue')
const loginBackgroundPath = path.join(process.cwd(), 'src', 'assets', 'login-mountain-lake-bg.jpg')

function cssRule(selector: string) {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return cssSource.match(new RegExp(`${escapedSelector}\\s*\\{[^}]*\\}`))?.[0] || ''
}

test('welcome section does not hardcode a specific merchant name', () => {
  assert.doesNotMatch(appSource, /欢迎回来，星享生活/)
  assert.match(appSource, /`👋 欢迎回来，\$\{merchantLabel\}`/)
})

test('welcome copy uses split reveal text animation without gsap dependency', () => {
  assert.match(appSource, /import SplitRevealText from '\.\/components\/SplitRevealText\.vue'/)
  assert.match(appSource, /<SplitRevealText[\s\S]*:text="`👋 欢迎回来，\$\{merchantLabel\}`"[\s\S]*tag="h1"/)
  assert.match(appSource, /<SplitRevealText[\s\S]*text="实时查看库存状态，收到新订单时请及时确认接单。"[\s\S]*tag="p"/)
  assert.doesNotMatch(splitRevealSource, /from 'gsap'|ScrollTrigger|GSAPSplitText/)
  assert.match(splitRevealSource, /IntersectionObserver/)
  assert.match(splitRevealSource, /split-reveal-char/)
  assert.match(splitRevealSource, /--split-index/)
  assert.match(cssSource, /\.split-reveal-char\s*\{[\s\S]*animation:\s*splitRevealIn/)
})

test('pause form is rendered inline with the expanded enabled product card', () => {
  assert.match(
    appSource,
    /<div v-for="p in filteredEnabled"[\s\S]*?<div v-if="expandingProduct === p\.rule_id" class="pause-form">/
  )
})

test('app persists merchant profile instead of relying only on token parsing', () => {
  assert.match(appSource, /localStorage\.getItem\('merchant_profile'\)/)
  assert.match(appSource, /extractMerchantSession/)
})

test('login page uses a single centered card without background image', () => {
  assert.match(appSource, /<aside class="sidebar" v-if="isLoggedIn">/)
  assert.match(appSource, /<main class="main" :class="\{ 'main-login': !isLoggedIn \}">/)
  assert.match(appSource, /<section v-if="!isLoggedIn" class="login-shell">/)
  assert.doesNotMatch(appSource, /GridDistortion/)
  assert.doesNotMatch(appSource, /loginDistortionImage/)
  assert.doesNotMatch(appSource, /class-name="login-distortion-bg"/)
  assert.match(appSource, /<section v-if="!isLoggedIn" class="login-shell">\s*<div class="login-form-panel">/)
  assert.match(appSource, /class="login-form-panel"/)
  assert.match(appSource, /<div class="login-form-panel">\s*<div class="login-card">/)
  assert.match(appSource, /class="login-form-copy"/)
  assert.match(appSource, /<h1>商户控制台<\/h1>/)
  assert.doesNotMatch(appSource, /<h1>登录商户控制台<\/h1>/)
  assert.match(appSource, /查看派单通知，管理商品接单状态/)
  assert.doesNotMatch(appSource, /<p class="login-eyebrow">商户登录<\/p>/)
  assert.doesNotMatch(appSource, /class="login-visual-panel"/)
  assert.doesNotMatch(appSource, /class="login-visual-card"/)
  assert.doesNotMatch(appSource, /class="login-visual-/)
  assert.doesNotMatch(appSource, /实时掌握每一次派单/)
  assert.doesNotMatch(appSource, /库存状态、接单控制、派单通知集中管理/)
  assert.doesNotMatch(appSource, /团团享设备租赁/)
  assert.doesNotMatch(appSource, /class="login-brand-anchor"/)
  assert.doesNotMatch(appSource, /class="login-brand-symbol"/)
  assert.doesNotMatch(appSource, /aria-label="团团享商户控制台"/)
  assert.doesNotMatch(appSource, /class="login-brand-panel"/)
  assert.doesNotMatch(appSource, /class="login-brand-mark"/)
  assert.doesNotMatch(appSource, /class="login-illustration"/)
  assert.doesNotMatch(appSource, /class="login-ill-card/)
  assert.doesNotMatch(appSource, /微信|Google|Apple|注册|验证码/)
  assert.doesNotMatch(appSource, /class="login-card-logo"/)
  assert.doesNotMatch(cssSource, /\.login-card-logo/)
  assert.equal(fs.existsSync(loginBackgroundPath), false)
  assert.match(cssSource, /\.main-login\s*\{[\s\S]*padding:\s*0/)
  assert.match(cssSource, /\.login-shell\s*\{[\s\S]*min-height:\s*100vh[\s\S]*grid-template-columns:\s*minmax\(320px,\s*420px\)/)
  assert.doesNotMatch(cssSource, /login-mountain-lake-bg|background:\s*url\(/)
  assert.match(cssSource, /\.login-shell\s*\{[\s\S]*position:\s*relative[\s\S]*overflow:\s*hidden/)
  assert.match(cssSource, /\.login-shell\s*\{[\s\S]*justify-content:\s*center/)
  assert.doesNotMatch(cssSource, /\.login-distortion-bg/)
  assert.match(cssSource, /\.login-form-panel\s*\{[\s\S]*z-index:\s*2/)
  assert.match(cssSource, /\.login-card\s*\{[\s\S]*width:\s*min\(380px,\s*100%\)[\s\S]*background:\s*rgba\(255,255,255,0\.94\)[\s\S]*box-shadow:\s*0 24px 70px/)
  assert.doesNotMatch(cssSource, /\.login-visual-/)
  assert.doesNotMatch(cssSource, /\.login-brand-anchor\s*\{/)
  assert.doesNotMatch(cssSource, /\.login-brand-symbol\s*\{/)
  assert.doesNotMatch(cssSource, /\.login-brand-panel\s*\{/)
  assert.doesNotMatch(cssSource, /\.login-illustration\s*\{/)
})

test('login page no longer ships a background animation component', () => {
  assert.equal(fs.existsSync(gridDistortionPath), false)
})

test('sidebar brand does not render meaningless standalone transfer icon', () => {
  assert.doesNotMatch(appSource, /class="sidebar-brand-icon"/)
  assert.doesNotMatch(cssSource, /\.sidebar-brand-icon/)
  assert.doesNotMatch(appSource, /<div class="sidebar-brand-icon">[\s\S]*?<\/div>/)
  assert.doesNotMatch(appSource, />转<\/div>/)
  assert.match(appSource, /<div class="sidebar-brand-copy"><strong>[\s\S]*?<\/strong><span>[\s\S]*?<\/span><\/div>/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto/)
})

test('app prefers merchant names from loaded products when available', () => {
  assert.match(appSource, /const merchantNameFromProducts = computed/)
  assert.match(appSource, /product\.merchant_name/)
})

test('app renders real dispatch notifications from api polling', () => {
  assert.match(appSource, /const notifications = ref/)
  assert.match(appSource, /const notificationsSummary = reactive/)
  assert.match(appSource, /const dispatchTrend = ref/)
  assert.match(appSource, /async function refreshNotifications/)
  assert.match(appSource, /api\.listNotifications/)
  assert.match(appSource, /setInterval\(refreshNotifications/)
  assert.match(appSource, /todayAssigned = computed\(\(\) => notificationsSummary\.today_count\)/)
  assert.match(appSource, /v-for="notification in (?:filteredNotifications|notifications)"/)
})

test('merchant products are polled so scheduled resume moves cards without manual refresh', () => {
  assert.match(appSource, /let productsTimer: ReturnType<typeof setInterval> \| null = null/)
  assert.match(appSource, /function startProductsPolling\(\)/)
  assert.match(appSource, /setInterval\(refreshProducts, 30000\)/)
  assert.match(appSource, /function stopProductsPolling\(\)/)
  assert.match(appSource, /startProductsPolling\(\)/)
  assert.match(appSource, /stopProductsPolling\(\)/)
})

test('login handles backend forced password change before entering merchant dashboard', () => {
  assert.match(appSource, /const forcePasswordChange = ref\(false\)/)
  assert.match(appSource, /const passwordChangeForm = reactive\(\{ newUsername: '', newPassword: '', confirmPassword: '' \}\)/)
  assert.match(appSource, /const pendingPasswordChangeToken = ref\(''\)/)
  assert.match(appSource, /if\s*\(result\.must_change_password\)\s*\{[\s\S]*pendingPasswordChangeToken\.value = result\.access_token[\s\S]*forcePasswordChange\.value = true[\s\S]*return/)
  assert.match(appSource, /async function completePasswordChange\(\)/)
  assert.match(appSource, /api\.changePassword\(newUsername, passwordChangeForm\.newPassword\)/)
  assert.match(appSource, /forcePasswordChange\.value = false/)
  assert.match(appSource, /loginForm\.username = newUsername/)
  assert.match(appSource, /sessionNotice\.value = '账号已设置成功，请使用新账号重新登录'/)
  assert.doesNotMatch(appSource, /completePasswordChange\(\)[\s\S]{0,900}enterMerchantDashboard\(result\)/)
  assert.match(appSource, /设置新账号和新密码/)
  assert.match(appSource, /新登录账号/)
  assert.match(appSource, /v-model="passwordChangeForm\.newUsername"/)
  assert.match(appSource, /autocomplete="username"/)
  assert.match(appSource, /autocomplete="new-password"/)
  assert.match(appSource, /@click="completePasswordChange"/)
  assert.match(appSource, /v-if="forcePasswordChange"/)
  assert.doesNotMatch(appSource, /result\.must_change_password[\s\S]{0,220}refreshProducts\(\)/)
})

test('forced password change inputs can toggle password visibility', () => {
  assert.match(appSource, /const passwordVisibility = reactive/)
  assert.match(appSource, /:type="passwordVisibility\.newPassword \? 'text' : 'password'"/)
  assert.match(appSource, /:type="passwordVisibility\.confirmPassword \? 'text' : 'password'"/)
  assert.match(appSource, /@click="passwordVisibility\.newPassword = !passwordVisibility\.newPassword"/)
  assert.match(appSource, /@click="passwordVisibility\.confirmPassword = !passwordVisibility\.confirmPassword"/)
  assert.match(appSource, /查看新密码/)
  assert.match(appSource, /查看确认新密码/)
  assert.match(appSource, /:aria-pressed="passwordVisibility\.newPassword"/)
  assert.match(appSource, /:aria-pressed="passwordVisibility\.confirmPassword"/)
  assert.match(appSource, /class="password-toggle-icon"/)
  assert.doesNotMatch(appSource, /👁/)
  assert.match(cssSource, /\.password-input-wrap/)
  assert.match(cssSource, /\.password-toggle/)
  assert.match(cssSource, /\.password-toggle-icon\s*\{[\s\S]*width:\s*18px[\s\S]*height:\s*18px/)
})

test('merchant login password input can toggle password visibility', () => {
  assert.match(appSource, /loginPassword:\s*false/)
  assert.match(appSource, /autocomplete="current-password"/)
  assert.match(appSource, /:type="passwordVisibility\.loginPassword \? 'text' : 'password'"/)
  assert.match(appSource, /@click="passwordVisibility\.loginPassword = !passwordVisibility\.loginPassword"/)
  assert.match(appSource, /查看密码/)
  assert.match(appSource, /隐藏密码/)
  assert.match(appSource, /:aria-pressed="passwordVisibility\.loginPassword"/)
})

test('merchant login validates required fields before requesting backend', () => {
  assert.match(appSource, /function getLoginValidationError\(\)/)
  assert.match(appSource, /const username = loginForm\.username\.trim\(\)/)
  assert.match(appSource, /return '请输入商户账号'/)
  assert.match(appSource, /return '请输入密码'/)
  assert.match(appSource, /const validationError = getLoginValidationError\(\)/)
  assert.match(appSource, /if \(validationError\) \{[\s\S]*error\.value = validationError[\s\S]*return[\s\S]*\}/)
  assert.match(appSource, /api\.login\(username, loginForm\.password\)/)
})

test('merchant login shows loading feedback and remember device option', () => {
  assert.match(appSource, /const rememberDevice = ref/)
  assert.match(appSource, /v-model="rememberDevice"/)
  assert.match(appSource, /记住此设备/)
  assert.match(appSource, /下次自动填入商户账号/)
  assert.match(appSource, /loading \? '登录中\.\.\.' : '登录'/)
  assert.match(appSource, /class="login-spinner"/)
  assert.match(cssSource, /\.login-spinner/)
  assert.match(cssSource, /@keyframes loginSpinner/)
})

test('merchant auth token avoids persistent localStorage storage', () => {
  assert.match(appSource, /const AUTH_TOKEN_KEY = 'merchant_token'/)
  assert.match(appSource, /function readStoredAuthToken\(\)/)
  assert.match(appSource, /sessionStorage\.getItem\(AUTH_TOKEN_KEY\)/)
  assert.match(appSource, /function persistAuthToken\(nextToken: string\)/)
  assert.match(appSource, /sessionStorage\.setItem\(AUTH_TOKEN_KEY, nextToken\)/)
  assert.match(appSource, /function clearAuthTokenStorage\(\)/)
  assert.match(appSource, /localStorage\.removeItem\(AUTH_TOKEN_KEY\)/)
  assert.doesNotMatch(appSource, /localStorage\.setItem\('merchant_token'/)
  assert.doesNotMatch(appSource, /localStorage\.getItem\('merchant_token'/)
})

test('logout distinguishes manual and expired session reasons', () => {
  assert.match(appSource, /type LogoutReason = 'manual' \| 'expired' \| 'password-reset-cancelled'/)
  assert.match(appSource, /const sessionNotice = ref\(''\)/)
  assert.match(appSource, /function logout\(reason: LogoutReason = 'manual'\)/)
  assert.match(appSource, /function getLogoutNotice\(reason: LogoutReason\)/)
  assert.match(appSource, /已安全退出登录/)
  assert.match(appSource, /登录已过期，请重新登录/)
  assert.match(appSource, /logout\('expired'\)/)
  assert.match(appSource, /@click="logout\('manual'\)"/)
  assert.match(appSource, /@click="logout\('password-reset-cancelled'\)"/)
  assert.match(appSource, /v-if="sessionNotice && !error"/)
  assert.match(cssSource, /\.login-notice/)
})

test('app resumes forced password change instead of booting dashboard from stored reset token', () => {
  assert.match(appSource, /if\s*\(tokenClaims\.value\?\.password_reset === true\)\s*\{/)
  assert.match(appSource, /pendingPasswordChangeToken\.value = token\.value/)
  assert.match(appSource, /token\.value = ''/)
  assert.match(appSource, /clearAuthTokenStorage\(\)/)
  assert.match(appSource, /forcePasswordChange\.value = true/)
  assert.match(appSource, /api\.setToken\(pendingPasswordChangeToken\.value\)/)
})

test('dashboard today stat uses api total order wording', () => {
  assert.match(appSource, /todayAssigned = computed\(\(\) => notificationsSummary\.today_count\)/)
  assert.match(appSource, /notificationsSummary\.today_count = result\.today_count/)
  assert.match(appSource, /<div class="stat-label">今日总单量<\/div>/)
  assert.match(appSource, /<div class="stat-sub">来自今日派单记录<\/div>/)
  assert.doesNotMatch(appSource, /<div class="stat-label">今日接单<\/div>/)
  assert.doesNotMatch(appSource, /<div class="stat-sub">等待派单分配<\/div>/)
})

test('dashboard renders native dispatch trend without loading chart libraries', () => {
  assert.doesNotMatch(appSource, /echarts/)
  assert.doesNotMatch(packageSource, /"echarts"/)
  assert.match(appSource, /const dispatchChartBars = computed\(\(\) => buildDispatchChartBars\(\)\)/)
  assert.match(appSource, /function buildDispatchChartBars\(\)/)
  assert.match(appSource, /class="dispatch-native-chart"/)
  assert.match(appSource, /class="dispatch-bar-segment"/)
  assert.match(appSource, /class="dispatch-chart-grid-line"/)
  assert.doesNotMatch(appSource, /图表加载中/)
  assert.match(appSource, /recentNotifications = computed\(\(\) => dashboardNotifications\.value\.slice\(0,\s*3\)\)/)
  assert.match(appSource, /newDispatchBurstCount\s*>\s*3/)
  assert.match(appSource, /goToNotifications/)
})

test('dashboard notifications show two-hour unread preview with read slide-away action', () => {
  assert.match(appSource, /import\s+\{\s*getRecentUnreadNotifications\s*\}\s+from\s+'\.\/notifications'/)
  assert.match(appSource, /const localReadNotificationIds = ref<Set<string>>\(new Set\(\)\)/)
  assert.match(appSource, /dashboardNotifications = computed\(\(\) => getRecentUnreadNotifications\(/)
  assert.match(appSource, /navUnreadCount = computed\(\(\) => navActive\.value === 'notifications' \? 0 : dashboardNotifications\.value\.length\)/)
  assert.match(appSource, /recentNotifications = computed\(\(\) => dashboardNotifications\.value\.slice\(0,\s*3\)\)/)
  assert.match(appSource, /hasMoreNotifications = computed\(\(\) => dashboardNotifications\.value\.length > recentNotifications\.value\.length\)/)
  assert.match(appSource, /查看全部 \{\{ dashboardNotifications\.length \}\} 条派单记录/)
  assert.match(appSource, /<TransitionGroup\s+name="notif-row-slide"/)
  assert.match(appSource, /@click="markNotificationRead\(notification\.id\)"/)
  assert.match(appSource, />已读<\/button>/)
  assert.match(appSource, /function markDashboardNotificationsRead\(\)[\s\S]*dashboardNotifications\.value\.map\(\(notification\) => notification\.id\)[\s\S]*localReadNotificationIds\.value = nextReadIds/)
  assert.match(appSource, /function goToNotifications\(\)[\s\S]*markDashboardNotificationsRead\(\)[\s\S]*navActive\.value = 'notifications'/)
  assert.match(cssSource, /\.notif-row-slide-leave-to\s*\{[\s\S]*translateX\(-120%\)/)
})

test('dashboard highlights freshly polled notification rows as merchant dispatch cards', () => {
  assert.match(appSource, /const highlightedNotificationIds = ref<Set<string>>\(new Set\(\)\)/)
  assert.match(appSource, /const notificationHighlightTimers = new Map<string, ReturnType<typeof setTimeout>>\(\)/)
  assert.match(appSource, /function markFreshNotificationHighlights\(notifications: MerchantNotification\[\]\)/)
  assert.match(appSource, /markFreshNotificationHighlights\(newUnreadItems\)/)
  assert.match(appSource, /highlightedNotificationIds\.has\(notification\.id\)/)
  assert.doesNotMatch(appSource, /class="notif-icon"/)
  assert.doesNotMatch(appSource, /aria-hidden="true">📦<\/span>/)
  assert.doesNotMatch(cssSource, /\.notif-icon\s*\{/)
  const notifRowRule = cssRule('.notif-row')
  assert.match(notifRowRule, /padding:\s*10px 14px/)
  assert.match(notifRowRule, /border-radius:\s*var\(--radius-md\)/)
  assert.match(notifRowRule, /background:\s*var\(--primary-pale\)/)
  assert.doesNotMatch(notifRowRule, /box-shadow:/)
  assert.equal(cssRule('.notif-row:hover'), '')
  assert.match(cssSource, /\.notif-row-new\s*\{[\s\S]*animation:\s*notificationCardPop/)
  assert.match(cssSource, /@keyframes notificationCardPop/)
})

test('dashboard notification list animates when expanded or collapsed', () => {
  assert.match(appSource, /<Transition\s+name="notif-collapse"/)
  assert.match(appSource, /<div class="notif-list" v-if="notifOpen">/)
  assert.match(cssSource, /\.notif-collapse-enter-active,\s*\.notif-collapse-leave-active\s*\{[\s\S]*transition:/)
  assert.match(cssSource, /\.notif-collapse-enter-from,\s*\.notif-collapse-leave-to\s*\{[\s\S]*opacity:\s*0/)
  assert.match(cssSource, /\.notif-collapse-enter-from,\s*\.notif-collapse-leave-to\s*\{[\s\S]*translateY\(-8px\)/)
  assert.match(cssSource, /\.notif-collapse-enter-from,\s*\.notif-collapse-leave-to\s*\{[\s\S]*max-height:\s*0/)
  assert.match(cssSource, /\.notif-collapse-enter-to,\s*\.notif-collapse-leave-from\s*\{[\s\S]*max-height:\s*420px/)
})

test('dashboard cards use scroll-triggered animated content effect without gsap', () => {
  assert.doesNotMatch(appSource, /from 'gsap'/)
  assert.doesNotMatch(appSource, /ScrollTrigger/)
  assert.match(appSource, /const visibleDashboardCardIds = ref<Set<string>>\(new Set\(\)\)/)
  assert.match(appSource, /data-dashboard-card-id="stat-today"/)
  assert.match(appSource, /data-dashboard-card-id="notifications"/)
  assert.match(appSource, /data-dashboard-card-id="dispatch-chart"/)
  assert.match(appSource, /visibleDashboardCardIds\.has\('stat-today'\)/)
  assert.match(appSource, /visibleDashboardCardIds\.value\.has\(dashboardCardId\)/)
  assert.match(cssSource, /\.dashboard-card\s*\{[\s\S]*opacity:\s*0[\s\S]*translateY\(42px\)[\s\S]*scale\(0\.96\)/)
  assert.match(cssSource, /\.dashboard-card\s*\{[\s\S]*transition:[\s\S]*opacity\s+0\.75s[\s\S]*transform\s+0\.75s/)
  assert.match(cssSource, /\.dashboard-card\.in-view\s*\{[\s\S]*opacity:\s*1[\s\S]*translateY\(0\)[\s\S]*scale\(1\)/)
})

test('dashboard dispatch chart stacks dispatch counts by product without machine line', () => {
  assert.match(appSource, /buildDispatchChartBars/)
  assert.match(appSource, /segments:\s*productOrder\.map/)
  assert.match(appSource, /title:\s*`\$\{product\}：\$\{count\} 单`/)
  assert.match(appSource, /notifications\.value/)
  assert.doesNotMatch(appSource, /focus:\s*'series'/)
  assert.doesNotMatch(appSource, /stack:\s*'dispatch-product'/)
  assert.doesNotMatch(appSource, /borderRadius:\s*\[6,\s*6,\s*0,\s*0\]/)
  assert.doesNotMatch(appSource, /charts\.LineChart/)
  assert.doesNotMatch(appSource, /day\.machine_count/)
})

test('dashboard dispatch chart shows custom tooltip on mouse hover and mobile tap', () => {
  assert.match(appSource, /const dispatchChartTooltip = reactive/)
  assert.match(appSource, /function showDispatchChartTooltip\(/)
  assert.match(appSource, /function hideDispatchChartTooltip\(\)/)
  assert.match(appSource, /@pointerenter="showDispatchChartTooltip\(\$event, segment, bar\)"/)
  assert.match(appSource, /@pointermove="showDispatchChartTooltip\(\$event, segment, bar\)"/)
  assert.match(appSource, /@click\.stop="showDispatchChartTooltip\(\$event, segment, bar\)"/)
  assert.match(appSource, /class="dispatch-chart-tooltip"/)
  assert.match(appSource, /dispatchChartTooltip\.product/)
  assert.match(appSource, /dispatchChartTooltip\.count/)
  assert.doesNotMatch(appSource, /:title="segment\.title"/)
  assert.doesNotMatch(cssSource, /cursor:\s*help/)
  assert.match(cssSource, /\.dispatch-chart-tooltip\s*\{/)
})

test('notifications page renders concise dispatch record fields with detailed time', () => {
  for (const label of ['时间', '商品', '订单号', '订单标题']) {
    assert.match(appSource, new RegExp(label))
  }
  for (const label of ['关键词词目', '命中关键词', '分配商户']) {
    assert.doesNotMatch(appSource, new RegExp(label))
  }
  assert.match(appSource, /formatDispatchTime\(notification\.assigned_at\)/)
  assert.match(appSource, /year:\s*'numeric'/)
  assert.match(appSource, /month:\s*'long'/)
  assert.match(appSource, /day:\s*'numeric'/)
  assert.match(appSource, /class="dispatch-record-table"/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.dispatch-record-table-wrap\s*\{[\s\S]*display:\s*none/)
})

test('dispatch record table header uses sticky glass styling', () => {
  assert.match(cssSource, /\.dispatch-record-table-wrap\s*\{[\s\S]*border-radius:\s*var\(--radius-lg\)/)
  assert.match(cssSource, /\.dispatch-record-table\s*\{[\s\S]*border-collapse:\s*separate[\s\S]*border-spacing:\s*0/)
  assert.match(cssSource, /\.dispatch-record-table thead\s*\{[\s\S]*position:\s*sticky[\s\S]*top:\s*0[\s\S]*z-index:\s*2/)
  assert.match(cssSource, /\.dispatch-record-table th\s*\{[\s\S]*background:\s*rgba\(255,255,255,0\.72\)/)
  assert.match(cssSource, /\.dispatch-record-table th\s*\{[\s\S]*backdrop-filter:\s*blur\(18px\)\s*saturate\(1\.25\)/)
  assert.match(cssSource, /\.dispatch-record-table th\s*\{[\s\S]*-webkit-backdrop-filter:\s*blur\(18px\)\s*saturate\(1\.25\)/)
})

test('merchant product cards hide matching keywords from merchants', () => {
  assert.doesNotMatch(appSource, /product-card-keywords/)
  assert.doesNotMatch(appSource, /product-card-kw/)
  assert.doesNotMatch(appSource, /p\.keywords\.some/)
})

test('product management collapses only enabled products so paused products stay easy to reach', () => {
  assert.match(appSource, /const enabledProductsCollapsed = ref\(false\)/)
  assert.match(appSource, /const isEnabledProductsCollapsed = computed\(\(\) => !hasProductSearch\.value && enabledProductsCollapsed\.value\)/)
  assert.match(appSource, /if\s*\(!enabledProductsCollapseTouched\.value\)\s*\{[\s\S]*enabledProductsCollapsed\.value = disabledProducts\.value\.length > 0/)
  assert.match(appSource, /function toggleEnabledProductsCollapse\(\)/)
  assert.match(appSource, /class="product-group-header"/)
  assert.match(appSource, /@click="toggleEnabledProductsCollapse"/)
  assert.match(appSource, /v-if="isEnabledProductsCollapsed"\s+class="product-collapse-summary"/)
  assert.match(appSource, /v-if="!isEnabledProductsCollapsed"\s+class="product-grid"/)
  assert.match(appSource, /<div v-if="filteredDisabled\.length > 0" class="product-group">[\s\S]*?<div class="product-grid">/)
  assert.match(cssSource, /\.product-collapse-enter-active,\s*\.product-collapse-leave-active\s*\{[\s\S]*transition:/)
  assert.match(cssSource, /\.product-collapse-summary\s*\{[\s\S]*cursor:\s*pointer/)
})

test('product management supports confirmed bulk pause and resume with progress feedback', () => {
  assert.match(appSource, /type BulkAvailabilityMode = 'pause' \| 'resume'/)
  assert.match(appSource, /type PauseResumeMode = 'scheduled' \| 'manual'/)
  assert.match(appSource, /const bulkAvailabilityDialog = reactive/)
  assert.match(appSource, /const bulkAvailabilityDialogDescription = computed/)
  assert.match(appSource, /resumeMode: 'scheduled' as PauseResumeMode/)
  assert.match(appSource, /resumeAt: ''/)
  assert.match(appSource, /function openBulkAvailabilityDialog\(mode: BulkAvailabilityMode\)/)
  assert.match(appSource, /function selectedBulkProducts\(mode: BulkAvailabilityMode\)/)
  assert.match(appSource, /mode === 'pause' \? enabledProducts\.value : disabledProducts\.value/)
  assert.match(appSource, /async function confirmBulkAvailability\(\)/)
  assert.match(appSource, /api\.bulkUpdateAvailability\(ruleIds, available, \{ resumeAt: pauseResumeAt \}\)/)
  assert.match(appSource, /datetimeLocalToIso\(bulkAvailabilityDialog\.resumeAt\)/)
  assert.match(appSource, /bulkAvailabilityDialog\.resumeMode === 'scheduled'/)
  assert.match(appSource, /bulkAvailabilityDialog\.resumeMode === 'manual'/)
  assert.match(appSource, /手动恢复/)
  assert.match(appSource, /已成功 \$\{result\.success_count\} 件，失败 \$\{result\.failed_count\} 件，请稍后重试/)
  assert.match(appSource, /一键暂停全部/)
  assert.match(appSource, /一键恢复全部/)
  assert.match(appSource, /确认暂停全部接单？/)
  assert.match(appSource, /确认恢复全部接单？/)
  assert.match(appSource, /处理中 \{\{ bulkAvailabilityProgress\.current \}\}\/\{\{ bulkAvailabilityProgress\.total \}\}/)
  assert.match(appSource, /class="bulk-dialog-backdrop"/)
  assert.match(cssSource, /\.product-toolbar\s*\{[\s\S]*display:\s*flex/)
  assert.match(cssSource, /\.bulk-dialog-backdrop\s*\{[\s\S]*position:\s*fixed/)
})

test('enabled product status badge says actively receiving orders', () => {
  assert.match(appSource, /<span class="status-badge active">正在接单<\/span>/)
  assert.doesNotMatch(appSource, /<span class="status-badge active">可接单<\/span>/)
})

test('product cards label status update time and scheduled resume time clearly', () => {
  assert.match(appSource, /状态更新：\s*\{\{\s*relativeTime\(p\.updated_at\)\s*\}\}/)
  assert.match(appSource, /\{\{\s*pausedResumeLabel\(p\.resume_at\)\s*\}\}\s*·\s*状态更新：\s*\{\{\s*relativeTime\(p\.updated_at\)\s*\}\}/)
  assert.match(appSource, /return '恢复方式：手动恢复'/)
})

test('product card in-view animation class is controlled by vue state', () => {
  assert.match(appSource, /const visibleProductCardIds = ref<Set<string>>\(new Set\(\)\)/)
  assert.match(appSource, /data-rule-id/)
  assert.match(appSource, /visibleProductCardIds\.has\(p\.rule_id\)/)
  assert.match(appSource, /entry\.target\.getAttribute\('data-rule-id'\)/)
  assert.doesNotMatch(appSource, /classList\.add\('in-view'\)/)
  assert.doesNotMatch(appSource, /classList\.remove\('in-view'\)/)
})

test('product card observer does not redeclare visibility state in one block', () => {
  assert.doesNotMatch(
    appSource,
    /const wasVisible = nextVisibleIds\.has\(ruleId\)\s+const wasVisible = nextVisibleIds\.has\(ruleId\)/
  )
})

test('product cards play a safe scroll-return animation without hiding again', () => {
  assert.match(appSource, /const productCardsInViewportIds = ref<Set<string>>\(new Set\(\)\)/)
  assert.match(appSource, /const returningProductCardIds = ref<Set<string>>\(new Set\(\)\)/)
  assert.match(appSource, /function triggerProductCardReturn/)
  assert.match(appSource, /returningProductCardIds\.has\(p\.rule_id\)/)
  assert.match(appSource, /'scroll-return': returningProductCardIds\.has\(p\.rule_id\)/)
  assert.match(cssSource, /\.product-card\.scroll-return\s*\{[\s\S]*animation:\s*productCardReturn/)
  assert.match(cssSource, /@keyframes\s+productCardReturn/)
  const returnAnimation = cssSource.match(/@keyframes\s+productCardReturn\s*\{[\s\S]*?\n\}/)?.[0] || ''
  assert.doesNotMatch(returnAnimation, /opacity:\s*0/)
})

test('pause scheduled resume time panel uses a 0.58s elastic pop-in animation', () => {
  assert.match(appSource, /class="pause-form"/)
  assert.match(appSource, /const pauseForm = reactive\(\{ resumeAt: '', resumeMode: 'scheduled' as PauseResumeMode \}\)/)
  assert.match(appSource, /class="pause-resume-mode"/)
  assert.match(appSource, /定时自动恢复/)
  assert.match(appSource, /手动恢复/)
  assert.match(appSource, /type="datetime-local"/)
  assert.match(appSource, /v-if="pauseForm\.resumeMode === 'scheduled'"/)
  assert.match(appSource, /v-model="pauseForm\.resumeAt"/)
  assert.match(appSource, /api\.updateAvailability\(ruleId, false, \{ resumeAt: pauseResumeAt \}\)/)
  assert.match(appSource, /pauseForm\.resumeMode === 'scheduled'/)
  assert.match(appSource, /恢复接单时间/)
  assert.doesNotMatch(appSource, /暂停原因/)
  assert.match(cssSource, /\.pause-form\s*\{[\s\S]*animation:\s*pauseFormPop\s+0\.58s/)
  assert.match(cssSource, /\.pause-resume-mode/)
  assert.match(cssSource, /\.pause-form input\.pause-time-input/)
  assert.match(cssSource, /\.pause-form-hint/)
  assert.match(cssSource, /@keyframes\s+pauseFormPop/)
  assert.match(cssSource, /transform-origin:\s*top center/)
  const pauseAnimation = cssSource.match(/@keyframes\s+pauseFormPop\s*\{[\s\S]*?\n\}/)?.[0] || ''
  assert.match(pauseAnimation, /0%\s*\{[^}]*opacity:\s*0[^}]*translateY\(-(?:8|9|10|11|12)px\)[^}]*scale\(0\.97/)
  assert.match(pauseAnimation, /(?:55|56|58|60)%\s*\{[^}]*opacity:\s*1[^}]*translateY\([23]px\)[^}]*scale\(1\.01/)
  assert.match(pauseAnimation, /(?:74|76|78|80)%\s*\{[^}]*translateY\(-1px\)[^}]*scale\(0\.99/)
})

test('machine inventory page supports compact batch snapshot submission', () => {
  assert.match(appSource, /type InventorySourceType = 'owned' \| 'catalog'/)
  assert.match(appSource, /navActive === 'machineInventory'/)
  assert.match(appSource, /机器库存/)
  assert.match(appSource, /<h1 class="sr-only">机器库存<\/h1>/)
  assert.doesNotMatch(appSource, /class="inventory-page-header"/)
  assert.doesNotMatch(appSource, />选择机器<\/strong>/)
  assert.match(appSource, /placeholder="搜索机器"/)
  assert.doesNotMatch(appSource, /class="inventory-list-header"/)
  assert.doesNotMatch(appSource, /<h2>清单<\/h2>/)
  assert.doesNotMatch(appSource, /上报清单/)
  assert.doesNotMatch(appSource, /<span>库存数量<\/span>/)
  assert.doesNotMatch(appSource, /class="inventory-quantity-field"[\s\S]{0,160}<span>/)
  assert.match(appSource, /:aria-label="`\$\{item\.row\.product\} 库存数量`"/)
  assert.doesNotMatch(appSource, /<button type="button" class="btn btn-ghost" @click="removeInventoryRow\(row\.key\)">移除<\/button>/)
  assert.match(appSource, /class="btn btn-ghost inventory-remove-row"/)
  assert.match(appSource, /aria-label="移除"/)
  assert.match(appSource, /&times;/)
  assert.match(appSource, /<div class="inventory-layout">/)
  assert.doesNotMatch(appSource, /has-draft/)
  assert.doesNotMatch(appSource, /class="inventory-list-card"/)
  assert.doesNotMatch(appSource, /class="inventory-draft-list"/)
  assert.doesNotMatch(appSource, /class="inventory-draft-row"/)
  assert.doesNotMatch(appSource, /function clearInventoryRows\(\)/)
  assert.match(appSource, /function focusInventoryQuantityInput\(rowKey: string\)/)
  assert.match(appSource, /data-inventory-row-key/)
  assert.doesNotMatch(appSource, /data-inventory-row-key[\s\S]{0,240}placeholder="0"/)
  assert.match(appSource, /focusInventoryQuantityInput\(rowKey\)/)
  assert.match(appSource, /input\?\.scrollIntoView\(\{[\s\S]*block:\s*'center'[\s\S]*inline:\s*'nearest'[\s\S]*\}\)/)
  assert.doesNotMatch(appSource, /const inventorySourceMode/)
  assert.doesNotMatch(appSource, /class="inventory-source-tabs"/)
  assert.doesNotMatch(appSource, />\s*已有\s*<\/button>/)
  assert.doesNotMatch(appSource, />\s*全部\s*<\/button>/)
  assert.doesNotMatch(appSource, /我的商品/)
  assert.doesNotMatch(appSource, /平台机器库/)
  assert.doesNotMatch(appSource, /function inventorySourceText/)
  assert.match(appSource, /const inventoryOptionPool = computed\(\(\) => \[\.\.\.inventoryOptions\.owned, \.\.\.inventoryOptions\.catalog\]\)/)
  assert.match(appSource, /const inventoryRowByRuleId = computed\(\(\) =>[\s\S]*new Map\(inventoryRows\.value\.map\(\(row\) => \[row\.rule_id, row\]\)\)/)
  assert.match(appSource, /const rows = inventoryOptionPool\.value/)
  assert.doesNotMatch(appSource, /const rows = inventoryOptionPool\.value\.filter\(\(option\) => !inventorySelectedRuleIds\.value\.has\(option\.rule_id\)\)/)
  assert.match(appSource, /const filteredInventoryOptionRows = computed\(\(\) => \{[\s\S]*return options\.map\(\(option\) => \(/)
  assert.match(appSource, /row: inventoryRowByRuleId\.value\.get\(option\.rule_id\) \|\| null/)
  assert.doesNotMatch(appSource, /currentInventoryOptions/)
  assert.match(appSource, /return option\.source_type === 'owned' && option\.available === false \? '暂停' : ''/)
  assert.doesNotMatch(appSource, /return option\.available === false \? '暂停' : '可接'/)
  assert.doesNotMatch(appSource, /return option\.has_active_application \? '已申' : '待申'/)
  assert.match(appSource, /function shouldShowInventoryOptionStatus\(option: MerchantInventoryOption\)/)
  assert.match(appSource, /return option\.source_type === 'owned' && option\.available === false/)
  assert.doesNotMatch(appSource, /function shouldShowInventoryOptionStatus\(option: MerchantInventoryOption\)[\s\S]*return true[\s\S]*function addInventoryOption/)
  assert.match(appSource, /function inventoryOptionActionText\(option: MerchantInventoryOption\)/)
  assert.match(appSource, /inventorySelectedRuleIds\.value\.has\(option\.rule_id\)[\s\S]*`编辑 \$\{product\} 数量`[\s\S]*`选择 \$\{product\}`/)
  assert.doesNotMatch(appSource, /return option\.available === false \? '已暂停' : '接单中'/)
  assert.doesNotMatch(appSource, /return option\.has_active_application \? '已申请' : '待申请'/)
  assert.doesNotMatch(appSource, /<em class="inventory-chip">\{\{ inventorySourceText\(option\.source_type\) \}\}<\/em>/)
  assert.match(appSource, /v-for="item in filteredInventoryOptionRows"/)
  assert.match(appSource, /<span v-if="shouldShowInventoryOptionStatus\(item\.option\)" class="inventory-option-tags">[\s\S]*<em class="inventory-chip muted">\{\{ inventoryOptionStatusText\(item\.option\) \}\}<\/em>[\s\S]*<\/span>/)
  assert.match(appSource, /:aria-label="inventoryOptionActionText\(item\.option\)"/)
  assert.match(appSource, /:title="inventoryOptionActionText\(item\.option\)"/)
  assert.doesNotMatch(appSource, /class="inventory-add-text"/)
  assert.doesNotMatch(appSource, /inventorySelectedRuleIds\.has\(option\.rule_id\) \? '✓' : '\+'/)
  assert.doesNotMatch(appSource, /:disabled="inventorySelectedRuleIds\.has\(option\.rule_id\)"/)
  assert.match(appSource, /const existingRow = inventoryRows\.value\.find\(\(row\) => row\.rule_id === option\.rule_id\)/)
  assert.match(appSource, /if \(existingRow\) \{[\s\S]*focusInventoryQuantityInput\(existingRow\.key\)[\s\S]*return[\s\S]*\}/)
  assert.match(appSource, /inventoryNotice\.value = ''[\s\S]*inventoryError\.value = ''[\s\S]*inventorySearch\.value = ''[\s\S]*focusInventoryQuantityInput\(rowKey\)/)
  assert.match(appSource, /quantity:\s*String\(inventoryOptionLatestQuantity\(option\) \?\? ''\)/)
  assert.doesNotMatch(appSource, /已加入/)
  assert.doesNotMatch(appSource, /加入/)
  assert.match(appSource, /<small v-if="!item\.row && inventoryOptionLatestQuantity\(item\.option\) !== null">[\s\S]*\{\{ inventoryOptionLatestQuantity\(item\.option\) \}\} 台/)
  assert.doesNotMatch(appSource, /<small v-if="inventoryOptionLatestQuantity\(item\.option\) !== null">/)
  assert.doesNotMatch(appSource, /\{\{ row\.latestQuantity \}\} 台/)
  assert.doesNotMatch(appSource, /inventorySourceText\(row\.source_type\)/)
  assert.doesNotMatch(appSource, /上次 \{\{ inventoryOptionLatestQuantity\(option\) \}\} 台/)
  assert.doesNotMatch(appSource, /上次 \{\{ row\.latestQuantity \}\} 台/)
  assert.match(appSource, /function updateInventoryRowQuantity\(rowKey: string, event: Event\)/)
  assert.match(appSource, /const row = inventoryRows\.value\.find\(\(item\) => item\.key === rowKey\)/)
  assert.match(appSource, /row\.quantity = input\.value/)
  assert.match(appSource, /function handleInventoryQuantityEnter\(rowKey: string\)/)
  assert.match(appSource, /const rowIndex = inventoryRows\.value\.findIndex\(\(item\) => item\.key === rowKey\)/)
  assert.match(appSource, /hasValidInventorySnapshotQuantities\(\[currentRow\]\)/)
  assert.match(appSource, /focusInventoryQuantityInput\(nextRow\.key\)/)
  assert.match(appSource, /const incompleteRow = inventoryRows\.value\.find\(\(item\) => !hasValidInventorySnapshotQuantities\(\[item\]\)\)/)
  assert.match(appSource, /if \(incompleteRow\) \{[\s\S]*focusInventoryQuantityInput\(incompleteRow\.key\)[\s\S]*return[\s\S]*\}/)
  assert.match(appSource, /inventoryCanSubmit\.value[\s\S]*void submitInventorySnapshot\(\)/)
  assert.match(appSource, /function isInventoryRowQuantityInvalid\(row: InventoryDraftRow\)/)
  assert.match(appSource, /row\.quantity\.trim\(\)\.length > 0 && !hasValidInventorySnapshotQuantities\(\[row\]\)/)
  assert.match(appSource, /:class="\{ selected: Boolean\(item\.row\), invalid: item\.row \? isInventoryRowQuantityInvalid\(item\.row\) : false \}"/)
  assert.match(appSource, /:aria-invalid="isInventoryRowQuantityInvalid\(item\.row\) \? 'true' : 'false'"/)
  assert.match(appSource, /:value="item\.row\.quantity"[\s\S]*@input="updateInventoryRowQuantity\(item\.row\.key, \$event\)"/)
  assert.match(appSource, /@keydown\.enter\.prevent="handleInventoryQuantityEnter\(item\.row\.key\)"/)
  assert.match(appSource, /type="number"[\s\S]*inputmode="numeric"[\s\S]*min="0"[\s\S]*step="1"/)
  assert.match(appSource, /hasValidInventorySnapshotQuantities/)
  assert.match(appSource, /const inventoryCanSubmit = computed\(\(\) =>[\s\S]*inventoryRows\.value\.length > 0[\s\S]*hasValidInventorySnapshotQuantities\(inventoryRows\.value\)/)
  assert.match(appSource, /const inventorySubmitDisabled = computed\(\(\) =>[\s\S]*inventorySubmitting\.value \|\| !inventoryCanSubmit\.value/)
  assert.match(appSource, /async function submitInventorySnapshot\(\)[\s\S]*if \(inventorySubmitting\.value\) \{[\s\S]*return[\s\S]*\}[\s\S]*inventoryNotice\.value = ''/)
  assert.match(appSource, /api\.listInventoryOptions\(\)/)
  assert.match(appSource, /api\.listLatestInventory\(\)/)
  assert.match(appSource, /api\.submitInventorySnapshot/)
  assert.match(appSource, /class="inventory-picker-toolbar"/)
  assert.doesNotMatch(appSource, /inventoryRowsTotalQuantity/)
  assert.doesNotMatch(appSource, /库存合计/)
  assert.doesNotMatch(appSource, />\s*清空清单\s*<\/button>/)
  assert.doesNotMatch(appSource, /class="inventory-list-summary"/)
  assert.doesNotMatch(appSource, /class="inventory-summary-pill"/)
  assert.doesNotMatch(appSource, /class="inventory-list-actions"/)
  assert.doesNotMatch(appSource, /class="btn btn-ghost inventory-clear-draft"/)
  assert.doesNotMatch(appSource, /class="inventory-list-count"/)
  assert.doesNotMatch(appSource, /aria-label="清空清单"/)
  assert.doesNotMatch(appSource, /class="btn btn-ghost inventory-clear-draft"[\s\S]{0,220}>\s*清空\s*<\/button>/)
  assert.doesNotMatch(appSource, /class="inventory-empty inventory-draft-empty"/)
  assert.doesNotMatch(appSource, /从左侧加入机器/)
  assert.match(appSource, /<div v-if="inventoryRows\.length > 0" class="inventory-submit-footer">/)
  assert.match(appSource, /inventorySubmitting \? '提交中' : '提交'/)
  assert.doesNotMatch(appSource, /提交库存快照/)
  assert.match(appSource, /const inventorySearchDraftName = computed\(\(\) => inventorySearch\.value\.trim\(\)\)/)
  assert.match(appSource, /function openInventoryProductApplicationFromSearch\(\)[\s\S]*const product = inventorySearchDraftName\.value[\s\S]*productApplicationSearchInput\.value = product[\s\S]*productApplicationSearchQuery\.value = product[\s\S]*openInventoryFeedback\('product_application'\)[\s\S]*chooseNewProductApplicationFromSearch\(\)/)
  assert.match(appSource, /v-if="inventoryShouldShowEmptyState"[\s\S]*class="inventory-empty"[\s\S]*没有找到机器[\s\S]*申请新增/)
  assert.match(appSource, /v-if="inventorySearchHasNoMatches"[\s\S]*class="inventory-empty-apply"[\s\S]*@click="openInventoryProductApplicationFromSearch"/)
  assert.match(appSource, /v-if="navActive === 'machineInventory' && feedbackPanelExpanded"/)
  assert.doesNotMatch(appSource, /:class="\['inventory-feedback-section', \{ 'is-collapsed': !feedbackPanelExpanded \}\]"/)
  assert.doesNotMatch(appSource, /aria-label="申请\/反馈"/)
  assert.doesNotMatch(appSource, /title="申请\/反馈"/)
  assert.doesNotMatch(appSource, /class="inventory-feedback-title"/)
  assert.doesNotMatch(appSource, /class="btn btn-ghost inventory-feedback-open"/)
  assert.doesNotMatch(appSource, /v-if="!feedbackPanelExpanded"[\s\S]*@click="openInventoryFeedback\(\)"[\s\S]*>\s*…\s*<\/button>/)
  assert.match(appSource, /class="btn btn-ghost inventory-feedback-close"/)
  assert.match(appSource, /aria-label="收起申请\/反馈"/)
  assert.match(appSource, /title="收起申请\/反馈"/)
  assert.match(appSource, /@click="closeInventoryFeedback"[\s\S]*>\s*&times;\s*<\/button>/)
  assert.doesNotMatch(appSource, /class="btn btn-ghost inventory-feedback-collapse"[\s\S]{0,180}>\s*收起\s*<\/button>/)
  assert.doesNotMatch(appSource, /class="btn btn-ghost inventory-feedback-open"[\s\S]{0,240}>/)
  assert.doesNotMatch(appSource, />\s*…\s*<\/button>/)
  assert.doesNotMatch(appSource, />\s*申请\/反馈\s*<\/button>/)
  assert.doesNotMatch(appSource, /需要新增机器、反馈价格或页面问题时使用/)
  assert.doesNotMatch(cssSource, /\.inventory-feedback-open/)
  assert.match(cssRule('.inventory-feedback-close'), /width:\s*34px/)
  assert.match(cssRule('.inventory-feedback-close'), /height:\s*34px/)
  assert.doesNotMatch(cssSource, /\.inventory-feedback-collapse/)
  assert.match(appSource, /feedbackPanelExpanded/)
  assert.match(appSource, /openInventoryFeedback/)
  assert.doesNotMatch(appSource, /class="inventory-page-header"[\s\S]{0,400}提交库存快照[\s\S]{0,80}<\/button>/)
  assert.match(cssSource, /\.inventory-layout\s*\{/)
  assert.match(cssSource, /\.sr-only\s*\{[\s\S]*position:\s*absolute[\s\S]*width:\s*1px[\s\S]*height:\s*1px[\s\S]*overflow:\s*hidden/)
  assert.doesNotMatch(cssSource, /\.inventory-page-header/)
  assert.match(cssSource, /\.inventory-picker-toolbar\s*\{/)
  const inventoryLayoutRule = cssRule('.inventory-layout')
  assert.match(inventoryLayoutRule, /grid-template-columns:\s*minmax\(0,\s*584px\)/)
  assert.match(inventoryLayoutRule, /justify-content:\s*center/)
  assert.doesNotMatch(cssSource, /\.inventory-layout\.has-draft/)
  assert.doesNotMatch(cssSource, /\.inventory-list-card/)
  assert.match(cssRule('.inventory-picker-toolbar'), /grid-template-columns:\s*minmax\(0,\s*1fr\)/)
  assert.doesNotMatch(cssSource, /\.inventory-source-tabs/)
  const inventoryOptionRowRule = cssRule('.inventory-option-row')
  assert.match(inventoryOptionRowRule, /min-height:\s*46px/)
  assert.match(inventoryOptionRowRule, /grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto\s+auto\s+auto/)
  assert.match(inventoryOptionRowRule, /gap:\s*6px/)
  assert.match(inventoryOptionRowRule, /padding:\s*6px 9px/)
  assert.match(cssRule('.inventory-option-main'), /gap:\s*2px/)
  assert.match(cssRule('.inventory-option-select'), /background:\s*transparent/)
  assert.match(cssRule('.inventory-chip'), /min-height:\s*18px/)
  assert.doesNotMatch(cssSource, /\.inventory-add-text/)
  assert.match(cssRule('.inventory-empty'), /min-height:\s*40px/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.inventory-option-row\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto\s+76px\s+auto/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.inventory-layout\s*\{[\s\S]*grid-template-columns:\s*1fr/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.inventory-layout\s*\{[\s\S]*gap:\s*10px/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.inventory-picker-card\s*\{[\s\S]*padding:\s*12px[\s\S]*border-radius:\s*18px/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.inventory-picker-toolbar\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)[\s\S]*gap:\s*6px/)
  assert.doesNotMatch(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.inventory-source-tabs/)
  assert.doesNotMatch(cssSource, /\.inventory-draft-row/)
  assert.doesNotMatch(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.inventory-option-tags\s*\{[\s\S]*grid-column:\s*1\s*\/\s*2/)
  assert.doesNotMatch(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.inventory-add-text/)
  assert.doesNotMatch(cssSource, /\.inventory-list-summary/)
  assert.doesNotMatch(cssSource, /\.inventory-summary-pill/)
  assert.doesNotMatch(cssSource, /\.inventory-list-header/)
  assert.doesNotMatch(cssSource, /\.inventory-list-actions\s*\{/)
  assert.doesNotMatch(cssSource, /\.inventory-list-count\s*\{/)
  assert.doesNotMatch(cssSource, /\.inventory-clear-draft\s*\{/)
  assert.match(cssSource, /\.inventory-submit-footer\s*\{/)
  assert.match(cssRule('.inventory-submit-footer'), /grid-template-columns:\s*minmax\(0,\s*1fr\)/)
  assert.match(cssSource, /\.inventory-submit-footer\s+\.btn-primary\s*\{[\s\S]*width:\s*100%/)
  const invalidInventoryOptionRowRule = cssRule('.inventory-option-row.invalid')
  assert.match(invalidInventoryOptionRowRule, /border-color:\s*rgba\(220,38,38,0\.32\)/)
  assert.match(invalidInventoryOptionRowRule, /background:\s*rgba\(254,226,226,0\.46\)/)
  assert.doesNotMatch(cssSource, /\.inventory-draft-main/)
  assert.doesNotMatch(cssSource, /\.inventory-quantity-field span/)
  assert.match(cssRule('.inventory-quantity-field input'), /min-height:\s*30px/)
  const invalidInventoryQuantityInputRule = cssRule('.inventory-option-row.invalid .inventory-quantity-field input')
  assert.match(invalidInventoryQuantityInputRule, /border-color:\s*rgba\(220,38,38,0\.55\)/)
  assert.match(invalidInventoryQuantityInputRule, /background:\s*#fff7f7/)
  assert.match(cssRule('.inventory-quantity-field input[type="number"]'), /appearance:\s*textfield/)
  assert.match(cssSource, /\.inventory-quantity-field input\[type="number"\]::-webkit-outer-spin-button,\s*\.inventory-quantity-field input\[type="number"\]::-webkit-inner-spin-button\s*\{[\s\S]*-webkit-appearance:\s*none/)
  assert.match(cssRule('.inventory-remove-row'), /width:\s*30px/)
  assert.match(cssRule('.inventory-remove-row'), /height:\s*30px/)
  assert.doesNotMatch(cssSource, /\.inventory-draft-empty/)
  assert.match(cssSource, /\.inventory-empty-apply\s*\{/)
  assert.match(cssSource, /\.inventory-feedback-section\s*\{/)
  assert.doesNotMatch(cssSource, /\.inventory-feedback-section\.is-collapsed/)
  assert.doesNotMatch(cssSource, /\.inventory-feedback-title/)
})

test('machine inventory keeps selected rows visible while filtering options', () => {
  assert.match(appSource, /const inventoryOptionByRuleId = computed\(\(\) =>[\s\S]*new Map\(inventoryOptionPool\.value\.map\(\(option\) => \[option\.rule_id, option\]\)\)/)
  assert.match(appSource, /const selectedInventoryOptions = computed\(\(\) =>[\s\S]*inventoryRows\.value\.map\(\(row\) =>[\s\S]*inventoryOptionByRuleId\.value\.get\(row\.rule_id\)[\s\S]*source_type: row\.source_type[\s\S]*latest_quantity: row\.latestQuantity/)
  assert.match(appSource, /const filteredInventoryOptionRows = computed\(\(\) => \{[\s\S]*const selectedRuleIds = inventorySelectedRuleIds\.value[\s\S]*const options = \[[\s\S]*\.\.\.selectedInventoryOptions\.value,[\s\S]*\.\.\.filteredInventoryOptions\.value\.filter\(\(option\) => !selectedRuleIds\.has\(option\.rule_id\)\),[\s\S]*\][\s\S]*return options\.map\(\(option\) => \(/)
  assert.match(appSource, /const inventorySearchHasNoMatches = computed\(\(\) =>[\s\S]*Boolean\(inventorySearchDraftName\.value\)[\s\S]*filteredInventoryOptions\.value\.length === 0/)
  assert.match(appSource, /const inventoryShouldShowEmptyState = computed\(\(\) =>[\s\S]*inventorySearchHasNoMatches\.value \|\| filteredInventoryOptionRows\.value\.length === 0/)
  assert.match(appSource, /v-if="inventoryShouldShowEmptyState"[\s\S]*class="inventory-empty"[\s\S]*inventorySearchHasNoMatches \? '没有找到机器' : '暂无机器'/)
  assert.match(appSource, /v-if="inventorySearchHasNoMatches"[\s\S]*class="inventory-empty-apply"[\s\S]*@click="openInventoryProductApplicationFromSearch"/)
})

test('mobile layout moves primary navigation into a bottom tab bar', () => {
  assert.match(appSource, /class="nav-badge"[\s\S]*navUnreadCount/)
  assert.match(appSource, /navActiveIndex = computed\(\(\) => \(\{ dashboard: 0, products: 1, machineInventory: 2, notifications: 3 \}\[navActive\.value\] \?\? 0\)\)/)
  assert.match(appSource, /navActive === 'machineInventory'[\s\S]*机器库存[\s\S]*<\/button>/)
  assert.match(appSource, /navActive === 'notifications'[\s\S]*历史派单[\s\S]*class="nav-badge"/)
  assert.doesNotMatch(appSource, /navActive === 'feedback'[\s\S]*反馈[\s\S]*<\/button>/)
  assert.match(appSource, /class="nav-active-indicator"[\s\S]*'--nav-active-index': navActiveIndex/)
  assert.match(appSource, /@click="goToNotifications"[\s\S]*v-if="navUnreadCount > 0"[\s\S]*navUnreadCount > 99 \? '99\+' : navUnreadCount/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar\s*\{[\s\S]*position:\s*static[\s\S]*height:\s*auto/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand\s*\{[\s\S]*position:\s*sticky[\s\S]*top:\s*0/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-nav\s*\{[\s\S]*position:\s*fixed[\s\S]*bottom:\s*12px;[\s\S]*bottom:\s*calc\(12px \+ env\(safe-area-inset-bottom,\s*0px\)\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-nav\s*\{[\s\S]*grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-nav\s*\{[\s\S]*backdrop-filter:\s*blur\(4px\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-nav\s*\{[\s\S]*border-radius:\s*15px[\s\S]*background:\s*rgba\(255,255,255,0\.21\)[\s\S]*background-image:\s*linear-gradient\(135deg,\s*#ffffff4D,\s*#ffffff4D\s*\)[\s\S]*box-shadow:\s*0 5px 32px rgba\(0,0,0,0\.05\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-nav button\s*\{[\s\S]*flex-direction:\s*column/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.nav-active-indicator\s*\{[\s\S]*transform:\s*translateX\(calc\(var\(--nav-active-index,\s*0\) \* \(100% \+ 4px\)\)\)[\s\S]*transition:\s*transform 0\.28s cubic-bezier\(0\.2,\s*0\.9,\s*0\.2,\s*1\.18\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-nav button\.active\s*\{[\s\S]*background:\s*transparent/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-nav button\s*\{[\s\S]*z-index:\s*1/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.nav-badge\s*\{[\s\S]*position:\s*absolute/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.main:not\(\.main-login\)\s*\{[\s\S]*padding-bottom:\s*112px;[\s\S]*padding-bottom:\s*calc\(112px \+ env\(safe-area-inset-bottom,\s*0px\)\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*480px\)[\s\S]*\.sidebar-nav\s*\{[\s\S]*bottom:\s*10px;[\s\S]*bottom:\s*calc\(10px \+ env\(safe-area-inset-bottom,\s*0px\)\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*480px\)[\s\S]*\.main:not\(\.main-login\)\s*\{[\s\S]*padding-bottom:\s*108px;[\s\S]*padding-bottom:\s*calc\(108px \+ env\(safe-area-inset-bottom,\s*0px\)\)/)
  assert.doesNotMatch(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-nav\s*\{[\s\S]*overflow-x:\s*auto/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand-user\s*\{[\s\S]*display:\s*grid/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand-logout\s*\{[\s\S]*display:\s*inline-flex/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-user\s*\{[\s\S]*display:\s*none/)
})

test('mobile touch interactions suppress native tap highlight while preserving focus-visible', () => {
  assert.match(cssSource, /@media\s*\(hover:\s*none\)\s*and\s*\(pointer:\s*coarse\)\s*\{[\s\S]*-webkit-tap-highlight-color:\s*transparent/)
  assert.match(cssSource, /@media\s*\(hover:\s*none\)\s*and\s*\(pointer:\s*coarse\)\s*\{[\s\S]*button,\s*a,\s*\[role="button"\],\s*\[role="tab"\],[\s\S]*\.sidebar-nav button,[\s\S]*\.feedback-tab,[\s\S]*\.product-card[\s\S]*tap-highlight-color:\s*transparent/)
  assert.match(cssSource, /@media\s*\(hover:\s*none\)\s*and\s*\(pointer:\s*coarse\)\s*\{[\s\S]*touch-action:\s*manipulation/)
  assert.match(cssSource, /button:focus:not\(:focus-visible\),[\s\S]*\[role="tab"\]:focus:not\(:focus-visible\)\s*\{[\s\S]*outline:\s*none/)
  assert.match(cssSource, /button:focus-visible,[\s\S]*\[role="tab"\]:focus-visible\s*\{[\s\S]*outline:\s*2px solid rgba\(159,232,112,0\.78\)/)
})

test('merchant inventory page embeds lightweight product application and feedback flows', () => {
  assert.match(appSource, /const feedbackRecords = ref<MerchantFeedbackRecord\[\]>\(\[\]\)/)
  assert.match(appSource, /const feedbackCenterMode = ref<FeedbackCenterMode>\('product_application'\)/)
  assert.match(appSource, /const productApplicationOptions = ref<MerchantProductApplicationOption\[\]>\(\[\]\)/)
  assert.match(appSource, /const productApplicationSearchInput = ref\(''\)/)
  assert.match(appSource, /const productApplicationSearchQuery = ref\(''\)/)
  assert.match(appSource, /const productApplicationPickerOpen = ref\(false\)/)
  assert.match(appSource, /const productApplicationRecords = ref<MerchantProductApplicationRecord\[\]>\(\[\]\)/)
  assert.match(appSource, /const submissionRecordsExpanded = ref\(false\)/)
  assert.match(appSource, /const submissionRecords = computed/)
  assert.match(appSource, /const visibleSubmissionRecords = computed/)
  assert.match(appSource, /const hasHiddenSubmissionRecords = computed/)
  assert.match(appSource, /const filteredProductApplicationOptions = computed/)
  assert.match(appSource, /async function refreshSubmissionRecords\(\)/)
  assert.match(appSource, /api\.listFeedback\(\)/)
  assert.match(appSource, /api\.listProductApplicationOptions\(\)/)
  assert.match(appSource, /api\.listProductApplications\(\)/)
  assert.match(appSource, /async function submitExistingProductApplication\(\)/)
  assert.match(appSource, /async function submitNewProductApplication\(\)/)
  assert.match(appSource, /async function submitProductApplication\(\)/)
  assert.match(appSource, /async function submitExistingProductApplication\(\)[\s\S]*const payload = \{[\s\S]*application_type: 'existing_product'[\s\S]*api\.submitProductApplication\(payload\)/)
  assert.match(appSource, /async function submitNewProductApplication\(\)[\s\S]*const payload = \{[\s\S]*application_type: 'new_product'[\s\S]*api\.submitProductApplication\(payload\)/)
  assert.match(appSource, /function applyProductApplicationSearch\(\)/)
  assert.match(appSource, /function selectProductApplicationOption\(productId: string\)/)
  assert.match(appSource, /function toggleSubmissionRecords\(\)/)
  assert.match(appSource, /async function submitIssueFeedback\(\)/)
  assert.match(appSource, /async function submitPriceFeedback\(\)/)
  assert.match(appSource, /async function submitIssueFeedback\(\)[\s\S]*const payload = \{[\s\S]*type: 'issue'[\s\S]*api\.submitFeedback\(payload\)/)
  assert.match(appSource, /async function submitPriceFeedback\(\)[\s\S]*const payload = \{[\s\S]*type: 'price_suggestion'[\s\S]*api\.submitFeedback\(payload\)/)
  assert.match(appSource, /class="product-application-search"/)
  assert.match(appSource, /v-model="productApplicationSearchInput"/)
  assert.doesNotMatch(appSource, /<button type="button" class="btn btn-ghost" @click="applyProductApplicationSearch">搜索<\/button>/)
  assert.doesNotMatch(appSource, /class="btn btn-ghost product-application-toggle"/)
  assert.doesNotMatch(appSource, /class="btn btn-ghost product-application-clear"/)
  assert.doesNotMatch(appSource, /function clearProductApplicationSearch\(\)/)
  assert.doesNotMatch(appSource, /function toggleProductApplicationPicker\(\)/)
  assert.match(appSource, /class="product-application-combobox"/)
  assert.match(appSource, /class="product-application-panel"/)
  assert.match(appSource, /v-if="productApplicationPickerOpen"/)
  assert.match(appSource, /v-for="option in filteredProductApplicationOptions"/)
  assert.match(appSource, /product-application-option/)
  assert.doesNotMatch(appSource, /<span>选择<\/span>/)
  assert.match(appSource, /class="product-application-selected"/)
  assert.doesNotMatch(appSource, /<button type="button" @click="openProductApplicationPicker\(\)">更换<\/button>/)
  assert.match(appSource, /class="product-application-selected"[\s\S]*role="button"[\s\S]*@click="openProductApplicationPicker\(\)"/)
  assert.match(appSource, /class="product-application-selected"[\s\S]*@keydown\.enter\.prevent="openProductApplicationPicker\(\)"/)
  assert.match(appSource, /price_per_day: priceFeedbackRequiresPrice\.value \? pricePerDay : null/)
  assert.doesNotMatch(appSource, /<template v-if="navActive === 'feedback'">/)
  assert.doesNotMatch(appSource, /反馈中心/)
  assert.match(appSource, /v-if="navActive === 'machineInventory' && feedbackPanelExpanded"/)
  assert.match(appSource, /class="inventory-feedback-strip"/)
  assert.doesNotMatch(appSource, /class="inventory-feedback-title"/)
  assert.doesNotMatch(appSource, /aria-label="申请\/反馈"/)
  assert.doesNotMatch(appSource, /需要新增机器、反馈价格或页面问题时使用/)
  assert.match(appSource, /商品申请/)
  assert.match(appSource, /问题 \/ 价格反馈/)
  assert.doesNotMatch(appSource, /class="feedback-form-header"/)
  assert.doesNotMatch(appSource, /<h2>商品申请<\/h2>/)
  assert.doesNotMatch(appSource, /<h2>问题 \/ 价格反馈<\/h2>/)
  assert.doesNotMatch(appSource, /先搜索商品，找不到时可以直接申请新增商品。/)
  assert.doesNotMatch(appSource, /已有商品：商品库中存在的商品名称/)
  assert.doesNotMatch(appSource, /申请已有商品/)
  assert.doesNotMatch(appSource, /<label>申请类型<\/label>/)
  assert.doesNotMatch(appSource, /switchProductApplicationMode/)
  assert.doesNotMatch(appSource, /const productApplicationMode = ref/)
  assert.match(appSource, /搜索商品，或输入想申请的新商品/)
  assert.match(appSource, /没有找到「/)
  assert.match(appSource, /申请新增商品「/)
  assert.match(appSource, />输入名称后申请新增<\/span>/)
  assert.doesNotMatch(appSource, /暂时没有可直接申请的商品，你可以输入商品名称后申请新增商品。/)
  assert.match(appSource, /已选择新增商品/)
  assert.doesNotMatch(appSource, /existingProductApplicationForm\.contact/)
  assert.doesNotMatch(appSource, /newProductApplicationForm\.contact/)
  assert.doesNotMatch(appSource, /issueFeedbackForm\.contact/)
  assert.doesNotMatch(appSource, /priceFeedbackForm\.contact/)
  assert.match(appSource, /待人工添加/)
  assert.match(appSource, /提交记录/)
  assert.doesNotMatch(appSource, /我的提交记录/)
  assert.doesNotMatch(appSource, /状态包含：已提交 \/ 审核中 \/ 待人工添加 \/ 已开通 \/ 已驳回 \/ 处理中 \/ 已处理。/)
  assert.match(appSource, /v-if="feedbackLoading \|\| submissionRecords\.length > 0"[\s\S]*class="feedback-record-panel"[\s\S]*:class="\{ 'is-compact': !submissionRecordsExpanded \}"/)
  assert.match(appSource, /class="feedback-record-summary"/)
  assert.match(appSource, /<template v-if="submissionRecordsExpanded">[\s\S]*v-for="record in visibleSubmissionRecords"/)
  assert.match(appSource, /hasHiddenSubmissionRecords/)
  assert.match(appSource, /展开/)
  assert.match(appSource, /收起/)
  assert.doesNotMatch(appSource, /class="feedback-record-actions"/)
  assert.doesNotMatch(appSource, /class="btn btn-ghost feedback-record-toggle"/)
  assert.doesNotMatch(appSource, /@click="refreshSubmissionRecords">刷新<\/button>/)
  assert.match(appSource, /placeholder="例如：我有该设备，可接单。"/)
  assert.doesNotMatch(appSource, /库存 2 台，支持同城配送/)
  assert.doesNotMatch(appSource, /关键词映射/)
  assert.doesNotMatch(appSource, /默认权重 1/)
  assert.doesNotMatch(appSource, /派单平台新增机器/)
  assert.doesNotMatch(appSource, /派单平台添加/)
  assert.doesNotMatch(appSource, /商户映射/)
  assert.match(appSource, /issueFeedbackForm\.issueType = option\.value/)
  assert.match(appSource, /v-model="issueFeedbackForm\.description"/)
  assert.match(appSource, /v-model="priceFeedbackForm\.product"/)
  assert.doesNotMatch(appSource, /点选后自动带入商品/)
  assert.match(appSource, /selectPriceIssueFeedback\(option\.value\)/)
  assert.match(appSource, /v-model="priceFeedbackForm\.pricePerDay"/)
  assert.match(appSource, />元\/天<\/span>/)
  assert.match(appSource, /提交价格建议/)
  assert.match(cssSource, /\.feedback-tabs\s*\{/)
  assert.doesNotMatch(cssSource, /\.feedback-form-header/)
  assert.match(cssSource, /\.product-application-search\s*\{/)
  assert.doesNotMatch(cssSource, /\.product-application-toggle/)
  assert.doesNotMatch(cssSource, /\.product-application-clear/)
  assert.match(cssSource, /\.product-application-combobox\s*\{/)
  assert.match(cssSource, /\.product-application-panel\s*\{/)
  assert.match(cssSource, /\.product-application-option\s*\{/)
  assert.doesNotMatch(cssSource, /\.product-application-option span\s*\{/)
  assert.match(cssSource, /\.product-application-create\s*\{/)
  assert.match(cssSource, /\.product-application-selected\s*\{/)
  assert.doesNotMatch(cssSource, /\.product-application-selected button/)
  assert.match(cssSource, /\.feedback-record-list\s*\{/)
  assert.match(cssSource, /\.feedback-record-panel\.is-compact\s*\{/)
  assert.match(cssSource, /\.feedback-record-summary\s*\{/)
  assert.doesNotMatch(cssSource, /\.feedback-record-actions\s*\{/)
  assert.doesNotMatch(cssSource, /\.feedback-record-toggle\s*\{/)
  assert.match(cssSource, /\.feedback-record-item\s*\{[\s\S]*padding:\s*10px 12px/)
  assert.match(cssSource, /\.feedback-record-item span\s*\{[\s\S]*font-size:\s*12px[\s\S]*-webkit-line-clamp:\s*1/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.feedback-record-item small\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /\.inventory-feedback-strip\s*\{/)
  assert.doesNotMatch(cssSource, /\.inventory-feedback-title/)
})

test('merchant feedback center switch uses compact segmented tabs', () => {
  assert.match(appSource, /class="feedback-tabs"/)
  assert.match(appSource, /class="feedback-tab-indicator"/)
  assert.match(appSource, /'--feedback-active-index': feedbackCenterMode === 'feedback' \? 1 : 0/)
  assert.match(appSource, /:class="\['feedback-tab', \{ active: feedbackCenterMode === 'product_application' \}\]"/)
  assert.match(appSource, /:class="\['feedback-tab', \{ active: feedbackCenterMode === 'feedback' \}\]"/)
  assert.doesNotMatch(appSource, /class="feedback-type-card"/)
  assert.match(cssSource, /\.feedback-tabs\s*\{/)
  assert.match(cssSource, /\.feedback-tab-indicator\s*\{[\s\S]*transform:\s*translateX\(calc\(var\(--feedback-active-index,\s*0\) \* \(100% \+ 6px\)\)\)[\s\S]*transition:\s*transform 0\.24s cubic-bezier\(0\.22,\s*0\.86,\s*0\.26,\s*1\.08\)/)
  assert.match(cssSource, /\.feedback-tab\s*\{[\s\S]*min-height:\s*46px/)
  assert.match(cssSource, /\.feedback-tab\.active\s*\{[\s\S]*background:\s*transparent[\s\S]*color:\s*var\(--positive-deep\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.feedback-tabs\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
})

test('merchant feedback actions open the embedded inventory feedback panel', () => {
  assert.match(appSource, /const feedbackPanelExpanded = ref\(false\)/)
  assert.match(appSource, /function openInventoryFeedback\(mode: FeedbackCenterMode = 'product_application'\)/)
  assert.match(appSource, /function goToFeedback\(mode: FeedbackCenterMode = 'product_application'\)/)
  assert.match(appSource, /function goToFeedback\(mode: FeedbackCenterMode = 'product_application'\)[\s\S]*openInventoryFeedback\(mode\)/)
  assert.match(appSource, /feedbackCenterMode\.value = mode/)
  assert.match(appSource, /feedbackPanelExpanded\.value = true/)
  assert.match(appSource, /navActive\.value = 'machineInventory'/)
  assert.match(appSource, /function scrollInventoryFeedbackIntoView\(\)/)
  assert.match(appSource, /document\.querySelector<HTMLElement>\('\.inventory-feedback-section'\)/)
  assert.match(appSource, /panel\?\.scrollIntoView\(\{[\s\S]*behavior:\s*'smooth'[\s\S]*block:\s*'start'[\s\S]*\}\)/)
  assert.match(appSource, /function openInventoryFeedback\(mode: FeedbackCenterMode = 'product_application'\)[\s\S]*scrollInventoryFeedbackIntoView\(\)/)
})

test('inventory feedback close and logout clear transient feedback state', () => {
  assert.match(appSource, /function resetFeedbackPanelState\(options: \{ clearDrafts\?: boolean \} = \{\}\)/)
  assert.match(appSource, /function resetFeedbackPanelState[\s\S]*clearProductApplicationPickerCloseTimer\(\)[\s\S]*clearPriceProductPickerCloseTimer\(\)[\s\S]*productApplicationPickerOpen\.value = false[\s\S]*priceProductPickerOpen\.value = false/)
  assert.match(appSource, /function resetFeedbackPanelState[\s\S]*if \(!options\.clearDrafts\) return[\s\S]*existingProductApplicationForm\.productId = ''[\s\S]*newProductApplicationForm\.product = ''[\s\S]*issueFeedbackForm\.description = ''[\s\S]*priceFeedbackForm\.product = ''/)
  assert.match(appSource, /function closeInventoryFeedback\(\) \{[\s\S]*feedbackPanelExpanded\.value = false[\s\S]*resetFeedbackPanelState\(\)[\s\S]*\}/)
  assert.match(appSource, /function logout\(reason: LogoutReason = 'manual'\)[\s\S]*resetFeedbackPanelState\(\{ clearDrafts: true \}\)/)
})

test('local preview feedback and application submissions stay client side', () => {
  assert.match(appSource, /createPreviewProductApplicationRecord/)
  assert.match(appSource, /createPreviewFeedbackRecord/)
  assert.match(appSource, /async function submitInventorySnapshot\(\)[\s\S]*if \(previewMode\) \{[\s\S]*latestInventoryItems\.value = items\.map[\s\S]*option\.latest_quantity = submitted\.quantity[\s\S]*inventoryRows\.value = \[\][\s\S]*return[\s\S]*api\.submitInventorySnapshot\(items\)/)
  assert.match(appSource, /async function confirmBulkAvailability\(\)[\s\S]*if \(previewMode\) \{[\s\S]*products\.value = products\.value\.map[\s\S]*available[\s\S]*resume_at[\s\S]*bulkAvailabilityDialog\.open = false[\s\S]*return[\s\S]*api\.bulkUpdateAvailability/)
  assert.match(appSource, /async function refreshSubmissionRecords\(\)[\s\S]*if \(previewMode\) \{[\s\S]*feedbackLoading\.value = false[\s\S]*return[\s\S]*api\.listFeedback/)
  assert.match(appSource, /async function refreshProductApplicationOptions\(\)[\s\S]*if \(previewMode\) \{[\s\S]*productApplicationOptionsLoading\.value = false[\s\S]*return[\s\S]*api\.listProductApplicationOptions/)
  assert.match(appSource, /async function submitExistingProductApplication\(\)[\s\S]*if \(previewMode\) \{[\s\S]*createPreviewProductApplicationRecord\(\{[\s\S]*application_type: 'existing_product'[\s\S]*return[\s\S]*api\.submitProductApplication/)
  assert.match(appSource, /async function submitNewProductApplication\(\)[\s\S]*if \(previewMode\) \{[\s\S]*createPreviewProductApplicationRecord\(\{[\s\S]*application_type: 'new_product'[\s\S]*return[\s\S]*api\.submitProductApplication/)
  assert.match(appSource, /async function submitIssueFeedback\(\)[\s\S]*if \(previewMode\) \{[\s\S]*createPreviewFeedbackRecord\(\{[\s\S]*type: 'issue'[\s\S]*return[\s\S]*api\.submitFeedback/)
  assert.match(appSource, /async function submitPriceFeedback\(\)[\s\S]*if \(previewMode\) \{[\s\S]*createPreviewFeedbackRecord\(\{[\s\S]*type: 'price_suggestion'[\s\S]*return[\s\S]*api\.submitFeedback/)
})

test('merchant existing product application uses compact product picker with selected card', () => {
  assert.match(appSource, /const mobilePickerMode = ref\(false\)/)
  assert.match(appSource, /function setupMobilePickerMode\(\)/)
  assert.match(appSource, /function blurActivePickerInputOnMobile\(\)/)
  assert.match(appSource, /function openProductApplicationPicker\(options: \{ blurActiveInput\?: boolean \} = \{\}\)/)
  assert.match(appSource, /function openProductApplicationPicker\(options: \{ blurActiveInput\?: boolean \} = \{\}\)[\s\S]*if \(options\.blurActiveInput !== false\) \{[\s\S]*void nextTick\(blurActivePickerInputOnMobile\)[\s\S]*\}/)
  assert.match(appSource, /function closeProductApplicationPickerSoon\(\)[\s\S]*if \(mobilePickerMode\.value\) return/)
  assert.doesNotMatch(appSource, /function toggleProductApplicationPicker\(\)/)
  assert.match(appSource, /function handleProductApplicationSearchInput\(\)[\s\S]*openProductApplicationPicker\(\{ blurActiveInput: false \}\)/)
  assert.match(appSource, /function selectProductApplicationOption\(productId: string\)[\s\S]*productApplicationPickerOpen\.value = false/)
  assert.match(appSource, /@focus="openProductApplicationPicker\(\)"/)
  assert.match(appSource, /@click="openProductApplicationPicker\(\)"/)
  assert.match(appSource, /@pointerdown="openProductApplicationPicker\(\)"/)
  assert.match(appSource, /@mousedown\.prevent="openProductApplicationPicker\(\)"/)
  assert.match(appSource, /@blur="closeProductApplicationPickerSoon"/)
  assert.match(appSource, /@input="handleProductApplicationSearchInput"/)
  assert.match(appSource, /v-model="productApplicationSearchInput"[\s\S]*:readonly="mobilePickerMode"/)
  assert.doesNotMatch(appSource, /@mousedown\.prevent="toggleProductApplicationPicker"/)
  assert.doesNotMatch(appSource, /@mousedown\.prevent="selectProductApplicationOption\(option\.product_id\)"/)
  assert.match(appSource, /@click="selectProductApplicationOption\(option\.product_id\)"/)
  assert.match(appSource, /class="product-application-selected"[\s\S]*role="button"[\s\S]*@click="openProductApplicationPicker\(\)"/)
  assert.match(appSource, /class="product-application-mobile-sheet"/)
  assert.match(appSource, /class="product-application-mobile-header"[\s\S]*aria-label="关闭"[\s\S]*&times;/)
  assert.doesNotMatch(appSource, /class="product-application-mobile-header"[\s\S]*>\s*关闭\s*<\/button>/)
  assert.match(appSource, /没有找到「/)
  assert.doesNotMatch(appSource, /@mousedown\.prevent="chooseNewProductApplicationFromSearch"/)
  assert.match(appSource, /@click="chooseNewProductApplicationFromSearch"/)
  assert.doesNotMatch(appSource, /class="product-application-list"/)
  assert.doesNotMatch(appSource, /product-application-list-item/)
  assert.match(cssSource, /\.product-application-mobile-sheet\s*\{/)
  assert.match(cssSource, /\.product-application-mobile-sheet\s*\{[\s\S]*grid-template-rows:\s*auto auto minmax\(0,\s*1fr\)[\s\S]*overflow:\s*hidden/)
  assert.match(cssSource, /\.product-application-mobile-header button\s*\{[\s\S]*width:\s*34px[\s\S]*height:\s*34px/)
  assert.match(cssSource, /\.product-application-mobile-list\s*\{[\s\S]*min-height:\s*0[\s\S]*-webkit-overflow-scrolling:\s*touch/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.product-application-panel\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media\s*\(min-width:\s*769px\)[\s\S]*\.product-application-mobile-sheet\s*\{[\s\S]*display:\s*none/)
})

test('merchant feedback option fields use styled animated choice chips instead of native selects', () => {
  assert.match(appSource, /const issueFeedbackOptions: Array<\{ value: MerchantIssueType; label: string \}>/)
  assert.match(appSource, /const priceIssueFeedbackOptions: Array<\{ value: MerchantPriceIssueType; label: string \}>/)
  assert.doesNotMatch(appSource, /<select v-model="issueFeedbackForm\.issueType"/)
  assert.doesNotMatch(appSource, /<select v-model="priceFeedbackForm\.priceIssueType"/)
  assert.match(appSource, /class="feedback-choice-group"[\s\S]*role="radiogroup"[\s\S]*v-for="option in issueFeedbackOptions"[\s\S]*role="radio"[\s\S]*@click="issueFeedbackForm\.issueType = option\.value"/)
  assert.match(appSource, /class="feedback-choice-group"[\s\S]*role="radiogroup"[\s\S]*v-for="option in priceIssueFeedbackOptions"[\s\S]*role="radio"[\s\S]*@click="selectPriceIssueFeedback\(option\.value\)"/)
  assert.match(cssSource, /\.feedback-choice-group\s*\{[\s\S]*display:\s*flex[\s\S]*flex-wrap:\s*wrap/)
  assert.match(cssSource, /\.feedback-choice\s*\{[\s\S]*border-radius:\s*var\(--radius-pill\)[\s\S]*transition:\s*transform 0\.18s cubic-bezier\(0\.22,\s*0\.86,\s*0\.26,\s*1\.08\)/)
  assert.match(cssSource, /\.feedback-choice\.active\s*\{[\s\S]*background:\s*rgba\(159,232,112,0\.22\)[\s\S]*color:\s*var\(--positive-deep\)/)
  assert.match(cssSource, /\.feedback-choice:active\s*\{[\s\S]*transform:\s*scale\(0\.98\)/)
})

test('merchant issue feedback avoids product wording and uses contextual guidance', () => {
  assert.doesNotMatch(appSource, /商品问题/)
  assert.doesNotMatch(appSource, /商品状态问题/)
  assert.match(appSource, /\{ value: 'product', label: '接单状态异常' \}/)
  assert.doesNotMatch(appSource, /用于反馈页面异常、派单异常、接单状态异常、登录账号问题。/)
  assert.doesNotMatch(appSource, /用于反馈页面异常、派单异常、接单状态异常、登录账号问题，也可以反馈机器推荐价格或型号问题。/)
  assert.match(appSource, /const issueFeedbackHelpText = computed/)
  assert.match(appSource, /const issueFeedbackPlaceholder = computed/)
  assert.match(appSource, /const issueFeedbackSubmitText = computed/)
  assert.match(appSource, /<p class="feedback-field-hint">\{\{ issueFeedbackHelpText \}\}<\/p>/)
  assert.match(appSource, /<textarea v-model="issueFeedbackForm\.description" :placeholder="issueFeedbackPlaceholder" \/>/)
  assert.match(appSource, /feedbackSubmitting \? '提交中\.\.\.' : issueFeedbackSubmitText/)
  assert.match(cssSource, /\.feedback-field-hint\s*\{[\s\S]*font-size:\s*12px[\s\S]*color:\s*var\(--mute\)/)
})

test('merchant price feedback shows suggested price only for unreasonable price reports', () => {
  assert.match(apiSource, /export type MerchantPriceIssueType = 'price_unreasonable' \| 'wrong_model' \| 'other'/)
  assert.match(appSource, /\{ value: 'price_unreasonable', label: '推荐价格不合理' \}/)
  assert.doesNotMatch(appSource, /\{ value: 'too_high', label: '价格偏高' \}/)
  assert.doesNotMatch(appSource, /\{ value: 'too_low', label: '价格偏低' \}/)
  assert.match(appSource, /const priceFeedbackRequiresPrice = computed\(\(\) => priceFeedbackForm\.priceIssueType === 'price_unreasonable'\)/)
  assert.match(appSource, /<div class="field" v-if="priceFeedbackRequiresPrice">[\s\S]*<label>建议价格<\/label>/)
  assert.match(appSource, /function selectPriceIssueFeedback\(value: MerchantPriceIssueType\)[\s\S]*priceFeedbackForm\.pricePerDay = ''/)
  assert.match(appSource, /price_per_day: priceFeedbackRequiresPrice\.value \? pricePerDay : null/)
  assert.match(appSource, /if \(!priceFeedbackRequiresPrice\.value && !reason\) \{[\s\S]*feedbackError\.value = '请填写原因说明'/)
  assert.doesNotMatch(appSource, /用于反馈推荐价格不合理、商品型号不准或其他价格推荐问题。/)
  assert.match(appSource, /const priceFeedbackSubmitText = computed/)
  assert.match(appSource, /feedbackSubmitting \? '提交中\.\.\.' : priceFeedbackSubmitText/)
})

test('merchant price feedback uses a custom product picker instead of native datalist', () => {
  assert.doesNotMatch(appSource, /list="feedback-product-options"/)
  assert.doesNotMatch(appSource, /<datalist id="feedback-product-options"/)
  assert.match(appSource, /const priceProductPickerOpen = ref\(false\)/)
  assert.doesNotMatch(appSource, /if \(mobilePickerMode\.value && priceProductPickerOpen\.value\) return feedbackProductOptions\.value/)
  assert.match(appSource, /const filteredFeedbackProductOptions = computed\(\(\) => \{[\s\S]*const keyword = priceFeedbackForm\.product\.trim\(\)\.toLowerCase\(\)/)
  assert.match(appSource, /function selectFeedbackProduct\(product: MerchantProduct\)/)
  assert.match(appSource, /function openPriceProductPicker\(options: \{ blurActiveInput\?: boolean \} = \{\}\)[\s\S]*if \(options\.blurActiveInput !== false\) \{[\s\S]*blurActivePickerInputOnMobile/)
  assert.match(appSource, /function openPriceProductPickerFromFocus\(\)[\s\S]*if \(mobilePickerMode\.value\) return[\s\S]*openPriceProductPicker\(\)/)
  assert.match(appSource, /function handlePriceProductInput\(\)[\s\S]*syncPriceFeedbackRuleId\(\)[\s\S]*openPriceProductPicker\(\{ blurActiveInput: false \}\)/)
  assert.doesNotMatch(appSource, /function togglePriceProductPicker\(\)/)
  assert.doesNotMatch(appSource, /function clearFeedbackProduct\(\)/)
  assert.match(appSource, /function closePriceProductPickerSoon\(\)[\s\S]*if \(mobilePickerMode\.value\) return/)
  assert.match(appSource, /class="feedback-product-picker"/)
  assert.match(appSource, /v-model="priceFeedbackForm\.product"[\s\S]*:readonly="mobilePickerMode"/)
  assert.match(appSource, /@click="openPriceProductPicker\(\)"/)
  assert.match(appSource, /@focus="openPriceProductPickerFromFocus"/)
  assert.doesNotMatch(appSource, /@pointerdown="openPriceProductPicker"/)
  assert.doesNotMatch(appSource, /@mousedown\.prevent="openPriceProductPicker"/)
  assert.doesNotMatch(appSource, /@touchstart\.passive="openPriceProductPicker"/)
  assert.match(appSource, /class="feedback-product-input-wrap"[\s\S]*@click="openPriceProductPicker\(\)"/)
  assert.doesNotMatch(appSource, /class="feedback-product-actions"/)
  assert.doesNotMatch(appSource, /class="feedback-product-clear"/)
  assert.doesNotMatch(appSource, /class="feedback-product-toggle"/)
  assert.doesNotMatch(appSource, /@mousedown\.prevent="togglePriceProductPicker"/)
  assert.doesNotMatch(appSource, /@mousedown\.prevent="clearFeedbackProduct"/)
  assert.match(appSource, /class="feedback-product-panel"/)
  assert.match(appSource, /v-for="product in filteredFeedbackProductOptions"/)
  assert.match(appSource, /@mousedown\.prevent="selectFeedbackProduct\(product\)"/)
  assert.match(appSource, /class="feedback-product-mobile-sheet"/)
  assert.match(appSource, /class="feedback-product-mobile-search"[\s\S]*v-model="priceFeedbackForm\.product"[\s\S]*@input="handlePriceProductInput"/)
  assert.match(appSource, /class="feedback-product-mobile-header"[\s\S]*aria-label="关闭"[\s\S]*&times;/)
  assert.doesNotMatch(appSource, /class="feedback-product-mobile-header"[\s\S]*>\s*关闭\s*<\/button>/)
  assert.match(cssSource, /\.feedback-product-picker\s*\{/)
  assert.doesNotMatch(cssSource, /\.feedback-product-actions/)
  assert.doesNotMatch(cssSource, /\.feedback-product-clear/)
  assert.doesNotMatch(cssSource, /\.feedback-product-toggle/)
  assert.match(cssSource, /\.feedback-product-panel\s*\{/)
  assert.match(cssSource, /\.feedback-product-option\s*\{/)
  assert.doesNotMatch(cssSource, /\.feedback-product-option small\s*\{/)
  assert.match(cssSource, /\.feedback-product-mobile-sheet\s*\{/)
  assert.match(cssSource, /\.feedback-product-mobile-sheet\s*\{[\s\S]*grid-template-rows:\s*auto auto minmax\(0,\s*1fr\)[\s\S]*overflow:\s*hidden/)
  assert.match(cssSource, /\.feedback-product-mobile-search input\s*\{[\s\S]*min-height:\s*44px[\s\S]*border-radius:\s*16px/)
  assert.match(cssSource, /\.feedback-product-input-wrap input\s*\{[\s\S]*padding-right:\s*12px/)
  assert.match(cssSource, /\.feedback-product-mobile-header button\s*\{[\s\S]*width:\s*34px[\s\S]*height:\s*34px/)
  assert.match(cssSource, /\.feedback-product-mobile-list\s*\{[\s\S]*min-height:\s*0[\s\S]*-webkit-overflow-scrolling:\s*touch/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.feedback-product-panel\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media\s*\(min-width:\s*769px\)[\s\S]*\.feedback-product-mobile-sheet\s*\{[\s\S]*display:\s*none/)
})

test('merchant feedback page maps not found backend errors to friendly copy', () => {
  assert.match(appSource, /function feedbackErrorMessage\(err: unknown, fallback: string\)/)
  assert.match(appSource, /message === 'Not Found'/)
  assert.match(appSource, /\\u53cd\\u9988\\u670d\\u52a1\\u6682\\u4e0d\\u53ef\\u7528/)
  assert.match(appSource, /feedbackErrorMessage\(err, '[^']+'\)/)
})

test('merchant feedback list is sorted newest first and clears stale records when unavailable', () => {
  assert.match(appSource, /function sortFeedbackRecords\(items: MerchantFeedbackRecord\[\]\)/)
  assert.match(appSource, /feedbackRecords\.value = sortFeedbackRecords\(result\.items \|\| \[\]\)/)
  assert.match(appSource, /if \(err instanceof ApiError && err\.status === 404\) \{[\s\S]*feedbackRecords\.value = \[\][\s\S]*\}/)
})

test('merchant price feedback submits integer daily price and resyncs selected product rule id', () => {
  assert.match(appSource, /syncPriceFeedbackRuleId\(\)[\s\S]*const pricePerDay = Number\(priceFeedbackForm\.pricePerDay\)/)
  assert.match(appSource, /Number\.isInteger\(pricePerDay\)/)
  assert.match(appSource, /price_per_day: priceFeedbackRequiresPrice\.value \? pricePerDay : null/)
  assert.match(appSource, /inputmode="numeric"[\s\S]*min="1"[\s\S]*step="1"/)
})

test('product pause panel links directly to price suggestion feedback with current product', () => {
  assert.match(appSource, /function goToPriceFeedback\(product: MerchantProduct\)/)
  assert.match(appSource, /feedbackCenterMode\.value = 'feedback'/)
  assert.match(appSource, /feedbackMode\.value = 'price_suggestion'/)
  assert.match(appSource, /priceFeedbackForm\.product = product\.product/)
  assert.match(appSource, /priceFeedbackForm\.ruleId = product\.rule_id/)
  assert.match(appSource, /navActive\.value = 'machineInventory'/)
  assert.match(appSource, /feedbackPanelExpanded\.value = true/)
  assert.match(appSource, /class="[^"]*pause-price-feedback-btn[^"]*"/)
  assert.match(appSource, /@click="goToPriceFeedback\(p\)"/)
  assert.match(appSource, /价格反馈/)
})

test('mobile merchant header uses compact glass app treatment', () => {
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand\s*\{[\s\S]*min-height:\s*56px[\s\S]*padding:\s*8px 16px[\s\S]*background:\s*rgba\(255,255,255,0\.62\)[\s\S]*border-bottom:\s*0[\s\S]*backdrop-filter:\s*blur\(18px\)\s*saturate\(1\.12\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand-user strong\s*\{[\s\S]*font-size:\s*14px[\s\S]*font-weight:\s*900/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand-user span\s*\{[\s\S]*font-size:\s*11px[\s\S]*opacity:\s*0\.62/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand-logout\s*\{[\s\S]*min-height:\s*28px[\s\S]*padding:\s*0 12px[\s\S]*border-radius:\s*999px[\s\S]*background:\s*rgba\(255,255,255,0\.56\)[\s\S]*color:\s*var\(--body\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.main:not\(\.main-login\)\s*\{[\s\S]*padding-top:\s*24px/)
  assert.match(cssSource, /@media\s*\(max-width:\s*480px\)[\s\S]*\.sidebar-brand\s*\{[\s\S]*min-height:\s*52px[\s\S]*padding:\s*8px 14px/)
})

test('mobile dashboard places today and paused stats on the same row', () => {
  assert.match(appSource, /class="stat-card stat-card-today"/)
  assert.match(appSource, /class="stat-card stat-card-online"/)
  assert.match(appSource, /class="stat-card stat-card-paused"/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.stats-row\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.stat-card-today\s*\{[\s\S]*grid-column:\s*1[\s\S]*grid-row:\s*1/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.stat-card-paused\s*\{[\s\S]*grid-column:\s*2[\s\S]*grid-row:\s*1/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.stat-card-online\s*\{[\s\S]*grid-column:\s*1\s*\/\s*-1[\s\S]*grid-row:\s*2/)
})

test('mobile sidebar brand uses merchant identity instead of static brand copy', () => {
  assert.match(appSource, /class="sidebar-brand-copy"/)
  assert.match(appSource, /class="sidebar-brand-user"[\s\S]*\{\{\s*merchantLabel\s*\}\}[\s\S]*\{\{\s*accountLabel\s*\}\}/)
  assert.match(appSource, /class="sidebar-brand-logout"[\s\S]*@click="logout\('manual'\)"/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.sidebar-brand-copy\s*\{[\s\S]*display:\s*none/)
})

test('mobile product header avoids squeezed title and description text', () => {
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.product-header\s*\{[\s\S]*flex-direction:\s*column[\s\S]*align-items:\s*stretch/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.product-header p\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media\s*\(max-width:\s*768px\)[\s\S]*\.product-search input\s*\{[\s\S]*width:\s*100%/)
})
